# frozen_string_literal: true

module Xuanji
  # Synchronise colour values between two XuanjiGrids.
  #
  # Why this exists:
  # - Kang's reading rules depend on the *colouring* of the grid.
  # - We store colour on each cell (x,y).
  # - The simplified grid is generated by character conversion, but its colours
  #   should match the corresponding traditional cell at the same coordinate.
  #
  # This service copies colours cell-by-cell by matching on (x,y).
  class SyncColors
    # NOTE: We deliberately support two keyword styles because earlier patches
    # and controllers used `trad:`/`simp:` while later code used
    # `source_grid:`/`target_grid:`.
    #
    # Preferred:
    #   Xuanji::SyncColors.call(source_grid: trad, target_grid: simp)
    # Back-compat:
    #   Xuanji::SyncColors.call(trad: trad, simp: simp)
    def self.call(trad: nil, simp: nil, source_grid: nil, target_grid: nil)
      from = source_grid || trad
      to   = target_grid || simp

      unless from && to
        raise ArgumentError, "Xuanji::SyncColors.call requires (source_grid:, target_grid:) or (trad:, simp:)"
      end

      new(source_grid: from, target_grid: to).call
    end

    def initialize(source_grid:, target_grid:)
      @source_grid = source_grid
      @target_grid = target_grid
    end

    # Returns number of target cells updated.
    def call
      source_by_xy = @source_grid.xuanji_cells.index_by { |c| [c.x, c.y] }
      updated = 0

      XuanjiCell.transaction do
        @target_grid.xuanji_cells.find_each do |target|
          source = source_by_xy[[target.x, target.y]]
          next unless source

          next if target.color == source.color

          target.update!(color: source.color)
          updated += 1
        end
      end

      updated
    end
  end
end
